FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY nginx.conf /etc/gninx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf